### ISSUE TITLE
Newest update

### ISSUE THREAD

**Issue by nomadism19** [n3d1117/appdb#85]
Adding ads is extremely unfortunate. This was the one decent app in the scene.

Second, the download button is permanently greyed out, forcing users to download from ddl site. Is this by design?

**Comment by kevinnguyrn** [comment]
it was uploaded by a completely different user and there is no mention of 1.14 here

**Comment by stev3fvcks** [comment]
> it was uploaded by a completely different user and there is no mention of 1.14 here

Hi guys, so this project is not be maintained by n3d anymore, so I started to maintain the project in order to keep it up-to-date with current appdb features.

I added [1.1.4](https://github.com/n3d1117/appdb/releases/tag/v1.1.4) to the releases today.



> Adding ads is extremely unfortunate. This was the one decent app in the scene.
> 
> Second, the download button is permanently greyed out, forcing users to download from ddl site. Is this by design?

The installation buttons should work as usual. What do you experience exactly?

About the ads: They are only shown upon requesting the installation of an app and only for users without appdb PLUS. If you don't want the ads, you can compile the IPA without the ads.

**Comment by stev3fvcks** [comment]
So the ads are now disabled by default. Installation buttons potentially not working should be fixed by that too. (Release [1.1.5](https://github.com/n3d1117/appdb/issues/74))
